#!/bin/sh

PATH=/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
cd ~

for file in $(find . -type f -name *.jar)
do
    res=$(jar -tf $file | grep "DiagServerLocator")
    # printf "Result: '%s'\n" $res
   	if [[ $res ]]; then
       printf "File: '%s'\n" $file
    #    printf "xx %s\n" $(jar -tf $file | grep "DiagServerLocator")
    fi
done